spring:
  application:
    name: lemur-admin
  cache:
    type: GENERIC
  main:
    allow-bean-definition-overriding: true
  http:
    converters:
      preferred-json-mapper: fastjson
  devtools:
    restart:
      enabled: false #是否开启开发者工具（true/false）
      additional-paths: src/main/java
  aop:
    proxy-target-class: true #false为启用jdk默认动态代理,true为cglib动态代理
  datasource:
    url: jdbc:mysql://localhost:3306/windbell?autoReconnect=true&useUnicode=true&characterEncoding=utf8&erverTimezone=UTC
    username: root
    password: root
    filters: wall,mergeStat
  redis:
    host: localhost
    port: 16379
    password: 123456
    database: 2
server:
  port: 9001 #项目端口

management:
  endpoints:
    web:
      exposure:
        include: "*" #暴露所有端点 默认是info和health
  endpoint:
    health:
      show-details: always #默认是never

jwt:
  header: Authorization   #http请求头所需要的字段
  secret: lemur_boot        #jwt秘钥
  expiration: 604800      #7天 单位:秒
  auth-path: auth         #认证请求的路径
  md5-key: randomKey      #md5加密混淆key

mybatis-plus:
  mapper-locations: classpath*:mapping/*.xml
  typeAliasesPackage: com.wupaas.boot.*.model
  global-config:
    id-type: id_worker  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用
  dbConfig:
    field-strategy: not_empty

j2cache:
  open-spring-cache: true
  config-location: j2cache-dev.properties

feign:
  hystrix:
    enabled: false
  client:
    config:
      default:  # 服务名，default表示所有服务
        connectTimeout: 10000
        readTimeout: 60000
        loggerLevel: full  # full | basic | none | headers
        #requestInterceptors: 拦截器

im:
  aliyun:
    accessKeyId: #
    accessSecret: #

file:
  channelId: qiniu
  qiniu:
    accesskey: #
    secretkey: #
    bucket: #

risk:
  idcard:
    channelId: juhe
  fraud:
    channelId: tencent
  juhe:
    idcard:
      appKey: #
  tencent:
    fraud:
      secretId: #
      secretKey: #


info:
  owner: Lemur
  version: 1.0
  app:
    name: lemur-admin
    version: 1.0
    description: 管理平台
    spring-boot-version: 2.0.6
